pipeline {
    agent any

    stages {
        stage('ImageScan') {
            steps {
                sh 'sudo trivy image thihathura/node'
            }
        }
    stages {
        stage('GitScan') {
            steps {
                sh 'sudo trivy repo https://github.com/ytechnologies2019/nodejs-dockerize-ci.git'
                }
            }
        }
    }
}