pipeline {
    agent {
        docker {
            image 'ubuntu'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -alht'
                sh 'hostname'
            }
        }
    }
}