pipeline {
    agent any

    environment {     
        DOCKERHUB_LOGIN= credentials('DOCKERHUB')     
    } 

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t node .'
            }
        }

        stage('Run') {
            steps {
                sh 'docker run -dp 3000:3000 --name node node'
            }
        }

        stage('ImageBuild') {
            steps {
                sh 'docker commit -m "node" -a "node" node thihathura/node'
            }
        }

        stage('DockerLogin') {
            steps {
                // sh 'docker login -u $DOCKERHUB_LOGIN_USR -p $DOCKERHUB_LOGIN_PSW'
                sh 'echo $DOCKERHUB_LOGIN_PSW | docker login -u $DOCKERHUB_LOGIN_USR --password-stdin'  
            }
        }

    }
        post { 
            always { 
                sh 'docker stop $(docker ps -aq) && docker system prune -fa'
                sh 'docker logout'
            }
        }
}
