pipeline {
    agent {
        docker { image 'docker:24.0.5-dind' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t node .'
            }
        }
        stage('Run') {
            steps {
                sh 'docker run -dp 3000:3000 --name node node'
            }
        }
        stage('ImageBuild') {
            steps {
                sh 'docker commit -m "node" -a "node" node thihathura/node'
            }
        }
        stage('Clear') {
            steps {
                sh 'docker stop $(docker ps -aq) && docker system prune -fa'
            }
        }
    }
}
